version: '3'
services:
  # postgres:
  #   image: postgres:latest
  #   container_name: my-postgres-container
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  haskell:
    build: .
    container_name: my-haskell-container
    # depends_on:
    #   - postgres
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data:
